name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclencher sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t clementbreg/front-end-react:${{ github.sha }} ./front-end-react

      - name: Push Docker image to DockerHub
        run: docker push clementbreg/front-end-react:${{ github.sha }}
