name: Multi-Service Versioning Pipeline

on:
  push:
    branches:
      - 'release-*'  # Déclencher pour toutes les branches commençant par "release-"

jobs:
  build_and_push_services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker images for order-service
        run: |
          TAG=$(echo "${{ github.ref }}" | cut -d'/' -f3)
          docker build -t clementbreg/order-service:$TAG ./path/to/order-service
          docker push clementbreg/order-service:$TAG

      - name: Build and Push Docker images for user-service
        run: |
          TAG=$(echo "${{ github.ref }}" | cut -d'/' -f3)
          docker build -t clementbreg/user-service:$TAG ./path/to/user-service
          docker push clementbreg/user-service:$TAG

      - name: Build and Push Docker images for front-end-react
        run: |
          TAG=$(echo "${{ github.ref }}" | cut -d'/' -f3)
          docker build -t clementbreg/front-end-react:$TAG ./front-end-react
          docker push clementbreg/front-end-react:$TAG
